name: Ansible check centos:centos7

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: ansible check with centos:centos7
      uses: roles-ansible/check-ansible-centos-centos7-action@master
      with:
        targets: "site.yml"
        group: 'local'
        hosts: 'localhost'
        requirements: 'requirements.yml'
